//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCrudSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int cod_usuario { get; set; }
        public string txt_user { get; set; }
        public string txt_password { get; set; }
        public string txt_nombre { get; set; }
        public string txt_apellido { get; set; }
        public string nro_doc { get; set; }
        public Nullable<int> cod_rol { get; set; }
        public Nullable<int> sn_activo { get; set; }
    
        public virtual Rol tRol { get; set; }
    }
}
